name: Run Shell commands
on: [push] # Trigger on push events

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Run shell commands
        run: |
          echo "Hello, World!"
          echo "This is a shell command running in GitHub Actions."
          echo "Current directory:"
          pwd
          echo "List of files:"
          ls -la